### PR TITLE
remove jcenter

### PR DESCRIPTION
**Pull request by jburel**
Remove jcenter

### CODE REVIEW

**Review by sbesson — APPROVED** [review]
The switch away from `jcenter` makes sense and matches https://blog.gradle.org/jcenter-shutdown.

I do not know enough about the impact of the removal of the `ReleasePlugin` class. I assume this is tested by the nightly CI infrastructure?

Also should this get released as `6.0.0` to mark the removal?

**Comment by jburel** [comment]
After a second thought, we do not use but other might so Better to replace jcenter only and mark the class as deprecated

**Comment by jburel** [comment]
Without the removal, suggested tag: ``5.5.3``

**Review by sbesson — APPROVED** [review]

**Comment by sbesson** [comment]
Is it possible to use this repository as a testing ground for the GitHub workflow-based deployment to artifactory?

**Comment by jburel** [comment]
You mean using https://github.com/jburel/action-workflows (after migration)

**Comment by sbesson** [comment]
Quite possibly. I don't know enough about the latest state of these actions and the next steps. Unlike the server components, the Gradle plugins have fairly low visibility/impact so it feels low cost to use this and try out automated deployments if we think the workflows are mature enough.

**Comment by jburel** [comment]
Automated will push to "staging" so there is a manual step to occur at the artifactory level unless we want to push to releases immediately. In that case the workflows need to be adjusted

**Comment by sbesson** [comment]
I am fine with starting with staging although I am increasingly considering we are too conservative and could reduce our manual burden. Python components are released to PyPI without such extra promotion step and the primary downside of an issue is that another release would be made.

Does the workflow also upload snapshots?

**Comment by jburel** [comment]
the current option is snapshot (default) or staging. I can easily add an extra step.
I will re-activate that work and test it using my repo

**Comment by jburel** [comment]
Tested the release workflow using my account
https://github.com/jburel/omero-artifact-plugin/blob/master/.github/workflows/gradle.yml

This is based on 2 repos
* https://github.com/jburel/action-gradle (Similar to action ice)
* https://github.com/jburel/action-workflows


Due to the current set up with the build system, the ``ARTIFACTORY_USER`` needs to have admin right.

**Comment by joshmoore** [comment]
:+1: for moving forward with those refactored repos.

**Comment by jburel** [comment]
i will migrate repository to the org and start adjusting the action on this repo so we can test with a tag

**Pull request merged**
