### PR TITLE
Update 

### PR DESCRIPTION
**Pull request by jburel**
This should fix some intermittent issues noticed in CI
* Bump version
* Remove deprecated code
* Remove usage of guava (The dependency is no longer shipped after the version bump)

### CODE REVIEW

**Review by joshmoore — APPROVED** [review]
Obviously, this whole plugin is still something of a mystery, but the changes don't look too scary and the build is green. :+1:

**Comment by sbesson** [comment]
Was [f874083](https://github.com/ome/omero-artifact-plugin/pull/20/commits/f874083f8f8a164ba9522b2d83d865c6fba146fb) motivated by a failure?

**Comment by sbesson** [comment]
Assuming a release of this plugin is looming (see https://github.com/ome/omero-artifact-plugin/pull/21), what is the plan on this PR?

**Comment by jburel** [comment]
> Was [f874083](https://github.com/ome/omero-artifact-plugin/pull/20/commits/f874083f8f8a164ba9522b2d83d865c6fba146fb) motivated by a failure?

no. Reducing dependencies since only one method was used

**Comment by jburel** [comment]
I will include the Java 11 fix only
The fact that the version is not bumped daily implies that it might have some side effects so I can get back to it afterwards

**Comment by jburel** [comment]
--exclude

**Pull request closed without merging**
