### PR TITLE
Update/552

### PR DESCRIPTION
**Pull request by rgozim**
- Removes duplicate classes located in buildSrc and src folders.
   - Main project now uses jar produced in buildSrc to obtain plugin classes and merges the 
     compiled classes into its distributable jar. The reason for doing this, is so that the plugin 
     definitions can point to a physical .class implementation located in the jar.

- Simplified publications. 
   - A bug exists wherein publications overwrite any previous publications, for example 
    `publishBinarys` running after `publishBinaryAndSources` will overwrite the maven- 
     attributes.xml and cancel the publishBinaryAndSources result (despite the results of 
     publishBinaryAndSources being located in the maven repository). The current behaviour will 
     throw and exception in gradle 5.6 (gradle/gradle#3835)

- Adds plugin for bringing functional testing configuration to gradle plugins

To Test:

Check builds are passing on merge-ci.

### CODE REVIEW

**Comment by jburel** [comment]
--exclude

**Comment by jburel** [comment]
PR excluded
It broke the build see https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-gradle-plugins-build/141/

**Comment by rgozim** [comment]
Tested with the latest commit and builds locally.

**Comment by joshmoore** [comment]
Since update/551 is exclude, I'm going to try to exclude this to see if I can get today's build building again.

https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-build-build/156/console

--exclude

**Comment by joshmoore** [comment]
Still failing, but now at a different location. Leaving @jburel and @rgozim to take a look this morning.

**Pull request closed without merging**
